
version: 2

models:
  - name: dbt_stg_wiki
    description: "A model that reflects the Hokkien (NAN) Wiki Data"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: dbt_int_wiki
    description: "A model that should contain the cleaned text_nan_poj data from stg_wiki."
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: dbt_int_wiki_transl
    description: "English translations of int_wiki"

  - name: dbt_int_wiki_joined
    description: "All Wiki Data Joined"

  - name: dbt_int_wiki_preunion
    description: "Prepping Wiki Data for Mart"

  - name: dbt_stg_omniglot
    description: "Omniglot Data. Contains nan_poj, nan_tc, en."

  - name: dbt_int_omniglot_preunion
    description: "Prepping Omniglot Data for Mart"

  - name: dbt_mart_samples
    description: "A mart of TestSet Data (aka Samples)."

  - name: dbt_ml_models_meta
    description: "ML Models. Some of these are ML Pipelines, instead of individual models."

  - name: dbt_ml_evaluators
    description: "Evaluators. Mainly just based on BLEU scores for now."

  - name: dbt_ml_testset_translations
    description: "Resulting translations of testset sample data using different ML_MODELS."

  - name: dbt_ml_testset_evaluations
    description: "Resulting Evaluations on ml_testset_translations."
    columns:
      - name: testset_translation_id
        description: "FK to ML_TESTSET_TRANSLATIONS"
      - name: evaluator
        description: "FK to ML_EVALUATORS"

  - name: dbt_ml_testset_evaluations_expanded
    description: "Expanded Evaluations, with their corresponding Sample Translations data. Via a join. Used to calculate summaries by translation-metadata."

  - name: dbt_ml_testset_evaluations_average
    description: "A summarized average of testsetevaluation results by Model and Evaluator."

